### ISSUE TITLE
Consider using Bitnami image for replication

### ISSUE THREAD

**Issue by D3f0** [15five/django-read-replicas#9]
Hi, I found your repository looking for a way to make django test use read replicas.

I think a good addition could be to use the bitnami's pre-prepared replication based on environment variables as described in this [gist](https://gist.github.com/JosimarCamargo/40f8636563c6e9ececf603e94c3affa7)

The code looks like:
```yaml
services:
  postgresql:
    image: 'docker.io/bitnami/postgresql:13'
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_PGAUDIT_LOG=READ,WRITE
      - POSTGRESQL_LOG_HOSTNAME=true
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_DATABASE=my_database
      - ALLOW_EMPTY_PASSWORD=yes
  replica:
    image: 'docker.io/bitnami/postgresql:13'
    ports:
      - '5433:5432'
    depends_on:
      - postgresql-primary
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_MASTER_HOST=postgresql-primary
      - POSTGRESQL_PGAUDIT_LOG=READ,WRITE
      - POSTGRESQL_LOG_HOSTNAME=true
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_PORT_NUMBER=5432

volumes:
  postgresql_master_data:
    driver: local
```
